name: MazeGenerator
version: 1.0
description: Generates mazes in Minecraft
author: gperm
main: me.gperm.mazegenerator.MazeGenerator
commands:
  test:
    description: Displays a message in chat
    usage: /test
